# Generated by Django 2.0.1 on 2018-01-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180127_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='2018-01-01-hny'),
            preserve_default=False,
        ),
    ]
